services:
  PostgreSQL:
    restart: always
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=store
    volumes:
      - ./src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data  # Persistent volume for data

  Redis:
    restart: always
    image: redis:5.0.0
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false

  shopping_cart:
    restart: always
    image: fp-cart:latest
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
      - FP_CART_ACCESS_TOKEN_SECRET_KEY=T3sT!FP!k4rt
      - FP_CART_JWT_SECRET_KEY=T3sTSekret!
      - 'FP_CART_JWT_CLAIM={"uuid": "89662e33-b03d-4e63-a69b-cafcc95929de"}'
      - FP_CART_ADMIN_USER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODk2NjJlMzMtYjAzZC00ZTYzLWE2OWItY2FmY2M5NTkyOWRlIn0.D5VMw2a9MHGGz0goeXvk9LkBaUF9ljoEy4dp987U6JI
      - FP_CART_PASSWORD_SALT=T3sT!S4lty
      - FP_CART_APP_ENV=test
volumes:
  postgres-data:
    driver: local
